name: dart_code_metrics_plugin_loader
description: This pubspec determines the version of the analyzer plugin to load.
version: 5.7.0-dev.2

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  analyzer: ">=5.1.0 <5.5.0"
  analyzer_plugin: ">=0.11.0 <0.12.0"
  linter: ^1.30.0
  cli_util: ^0.3.5
  source_span: ^1.9.1

dev_dependencies:
  lints: ^1.0.1
